server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-boston-frontend
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
